# Generated by Django 5.2 on 2025-04-21 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0002_alter_cashflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_flow.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_flow.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_flow.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_flow.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cash_flow.type'),
        ),
    ]
